version: '3.9'

services:
  db:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:14.1
    restart: unless-stopped
    networks:
      - postgres-network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_config:/docker-entrypoint-initdb.d/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    networks:
      - postgres-network
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ./db_config/server.json:/pgadmin4/servers.json

networks:
  postgres-network:
    driver: bridge